- name: Kubernetes sur Azure
  href: ./index.yml
- name: Vue d'ensemble
  items:
    - name: Kubernetes sur Azure
      href: container-service-intro-kubernetes.md
- name: Démarrages rapides
  expanded: true
  items:
    - name: Kubernetes sur Azure
      href: container-service-kubernetes-walkthrough.md
- name: Didacticiels
  items:
    - name: 1 - Créer des images de conteneur
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 - Créer un registre de conteneur
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: "3 -Créer un cluster\_Kubernetes"
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 - Exécuter l’application
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 - Mettre à l’échelle l’application
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 - Mettre à jour l’application
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 - Surveiller avec OMS
      href: container-service-tutorial-kubernetes-monitor.md
- name: Concepts
  items:
    - name: Principal de service – Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: Procédures
  items:
    - name: Kubernetes avec Windows
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Interface web de Kubernetes
      href: container-service-kubernetes-ui.md
    - name: Utiliser des graphiques Helm
      href: container-service-kubernetes-helm.md
    - name: Utiliser Jenkins avec ACS
      href: container-service-kubernetes-jenkins.md
    - name: Utiliser le brouillon avec ACS
      href: container-service-draft-up.md
    - name: Mettre à l’échelle le cluster
      href: container-service-scale.md
    - name: Surveiller
      items:
        - name: Surveiller avec OMS
          href: container-service-kubernetes-oms.md
        - name: Surveiller avec Datadog
          href: container-service-kubernetes-datadog.md
        - name: Surveiller avec Sysdig
          href: container-service-kubernetes-sysdig.md
        - name: Surveiller avec CoScale
          href: container-service-kubernetes-coscale.md
    - name: Déployer des applications Spring Boot
      items:
        - name: Déployer une application Spring Boot sur Linux dans Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Déployer une application Spring Boot sur un cluster Kubernetes dans Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Déployer une application Spring Boot à l’aide du plug-in fabric8 Maven
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Référence
  items:
    - name: Interface de ligne de commande Azure
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/container-service
- name: Ressources
  items:
    - name: Feuille de route Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Forum Aux Questions
      href: container-service-faq.md
    - name: Modèles – Moteur ACS
      href: 'https://github.com/Azure/acs-engine'
    - name: Tarification
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Disponibilité des régions
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Dépassement de capacité de la pile
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Vidéos
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'